### PR TITLE
Update golang to 1.17 and dependencies

### PR DESCRIPTION
**Pull request by msladek**
1. ran
```
go mod edit -go=1.17 && \
go get all && \
go mod tidy
```
2. updated golang to 1.17
  - in `Makefile`
  - in `.github/go/Dockerfile`
3. ~~removed `vendor` from `.gitignore`~~
  removed `vendor` dir

### CODE REVIEW

**Comment by msladek** [comment]
@hazcod any idea why the build is failing?

**Comment by hazcod** [comment]
@msladek FYI it's now a common practice to not rely on `vendor/` anymore but the local go mod cache.
Hence me removing it from git a couple of months ago.

**Comment by msladek** [comment]
@hazcod I see, but why then is there still a `vendor` dir on the master branch? shouldn't it be removed from the repo?

**Comment by hazcod** [comment]
@msladek Fair point, not sure where I forgot to push. Thanks!

**Pull request merged**
